config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  devise_for :users

  resources :teachers, only: %i[index show] do
    resources :reviews, only: [:new]
  end

  resources :reviews, only: [:create, :index, :destroy]

  get 'students/show'

  resources :bookings do
    member do
      get 'initiate_payment'
      post 'process_payment'
    end
  end

  resources :subjects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :subject
end

app/models/data_student.rb
class DataStudent < ApplicationRecord
  belongs_to :user
end

app/models/data_teacher.rb
class DataTeacher < ApplicationRecord
  belongs_to :user
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_many :reviews
  has_many :bookings
end

app/models/review.rb
class Review < ApplicationRecord
  # belongs_to :user
  belongs_to :user

end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # validates :first_name, :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  enum role: {
    Profesor: 0,
    Estudiante: 1,
  }

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :Profesor
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :city, :role, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :city, :role, :photo])
  end

  def article_params
    params.require(:user).permit(:title, :body, :photo)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :edit, :update, :destroy, :initiate_payment, :process_payment]



  def index
    @bookings = Booking.all
  end

  def new
    # cargar datos adicionales para el formulario
    @booking = Booking.new
    @subjects = Subject.all
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    if @booking.save
      # @booking.reload
      redirect_to initiate_payment_booking_path(@booking), notice: 'Realiza tu pago.'
    else
      render :new, status: :unprocessable_entity
    end
    
  end


  def initiate_payment
    @booking = Booking.find(params[:id])
  
    if @booking.present?
      if request.post?
        # Realiza aquí la lógica de procesamiento de pago
        # Si el pago es exitoso, actualiza el estado de la reserva a true
        @booking.update(status: true)
  
        redirect_to bookings_path, notice: "Reserva creada exitosamente"
      else
        flash.now[:error] = 'Error en la información de pago. Corrige los errores.'
        render :initiate_payment
      end
    else
      flash[:error] = 'Error: No se pudo obtener la información de la reserva.'
      redirect_to root_path
    end
  end
  

  def edit
    # La acción edit puede utilizar el before_action :set_booking
  end

  def update
    if @booking.update(booking_params)
      flash[:success] = 'Reserva actualizada exitosamente.'
      redirect_to booking_path(@booking)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    puts "Eliminando reserva #{params[:id]}"  # Agrega este mensaje de depuración
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_path, notice: 'La reserva ha sido eliminada exitosamente.' }
      format.json { head :no_content }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@booking) }
    end
  end

  def show
    @bookings = [@booking]
    # La acción show puede utilizar el before_action :set_booking
  end

  private

  def set_booking
    @booking = params[:id] == 'initiate_payment' ? nil : Booking.find(params[:id])
  end

  # def set_booking
  #   @booking = Booking.find(params[:id])
  # end

  def booking_params
    params.require(:booking).permit(:date, :time_in, :time_out, :subject_id)
  end

  def payment_params
    params.require(:payment).permit(:nombre_tarjeta, :numero_tarjeta)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    #set user
    @user = User.find(params[:calificated_user])
    #raise
    @review = Review.new(review_params)
    @review.user = @user
    # @review.rating = params[:review][:rating].to_i
    if @review.save
       redirect_to teacher_path(@user), notice: 'Revisión creada exitosamente.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @reviews = Review.all
  end

  def destroy
    @review = Review.find(params[:id])
    @review. destroy
    redirect_to reviews_path, notice: 'Revisión eliminada exitosamente';
  end

  private

  def review_params
    params.require(:review).permit(:comments, :rating)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def show
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[show edit update destroy]

  def index
    @subjects = Subject.all
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    @subject.user = current_user

    if @subject.save
      redirect_to subjects_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @subject.update(subject_params)
      redirect_to subject_path(@subject)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @subject.destroy
    redirect_to subjects_path, status: :see_other
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :grade_subject, :description)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @subjects = Subject.where(user_id: params[:id])
    @reviews = Review.where(user_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb

<div data-controller="modal">
  <div data-action="click->modal#closeOnBackdrop" data-modal-target="backdrop" class="modal-backdrop fade show"></div>
  <div data-modal-target="modal" class="modal fade show d-block" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg rounded-4">
      <div class="modal-content modal-content-centered rounded-4">
        <div class="modal-header">
          <h5>Reserva una clase de prueba</h5>
          <button type="button" class="btn-close" data-action="click->modal#close" style="color: #ff0000;"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for @booking, url: bookings_path, method: :post, html: { class: 'form' } do |form| %>
            <%= form.input :date, label: "Fecha", input_html: { class: 'form-control' }, html5:true %>
            <%= form.input :time_in, label: "Hora de inicio", input_html: { class: 'form-control' } %>
            <%= form.input :time_out, label: "Hora de finalización", input_html: { class: 'form-control' } %>
            <%#= form.input :subject_id, collection: @subjects, label: "Materias", input_html: { class: 'form-control' } %>
            <%= form.association :subject, collection: Subject.all %>
            <%= form.submit %>
            <div class="text-center">
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= console %>


app/views/bookings/create.html.erb
<h1>Booking#create</h1>
<p>Find me in app/views/booking/create.html.erb</p>


<!-- app/views/bookings/new.html.erb -->

app/views/bookings/destroy.html.erb
<h1>Booking#destroy</h1>
// app/views/bookings/destroy.js.erb
// Este archivo se ejecutará después de la eliminación asincrónica

// Puedes agregar aquí cualquier lógica adicional si es necesario
console.log('Reserva eliminada exitosamente.');

app/views/bookings/edit.html.erb
<!-- app/views/bookings/edit.html.erb -->
<h1>Editar Reserva</h1>

<%= render 'form', booking: @booking, subjects: @subjects %>

<%= link_to 'Volver a la reserva', booking_path(@booking) %>

app/views/bookings/index.html.erb
<h1>Listado de Reservas</h1>

<table>
  <!-- Table header -->
  <thead>
    <tr>
      <th>ID</th>
      <th>Fecha</th>
      <th>Hora de inicio</th>
      <th>Hora de finalización</th>
      <th>Materia</th>
      <th>Status</th>
      <th>Acciones</th>

    </tr>
  </thead>
  <tbody>

    <% @bookings.each do |booking| %>
      <% if booking.user_id == current_user.id %>
        <tr>
          <td><%= booking.id %></td>
          <td><%= booking.date %></td>
          <td><%= booking.time_in %></td>
          <td><%= booking.time_out %></td>
          <td><%= booking.subject.name %></td>
          <td><p>Pagado</p></td>


          <td>
              <%= link_to 'Editar', edit_booking_path(booking), class: 'btn btn-warning' %>
              <%#= link_to 'Eliminar', booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>


<div>
  <%= link_to 'Volver a la lista de reservas', bookings_path %>
</div>

app/views/bookings/initiate_payment.html.erb
<!-- app/views/bookings/initiate_payment.html.erb -->
<!-- app/views/bookings/initiate_payment.html.erb -->
<h1>Seleccione el método de pago</h1>

<% if @booking %>
  <%= form_with(model: @booking, url: process_payment_booking_path(@booking), method: :post) do |form| %>
    <% if @booking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@booking.errors.count, "error") %> prohibieron que se guardara la reserva:</h2>

        <ul>
          <% @booking.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Agregar los campos del formulario de pago -->
    <div class="field">
      <%= form.label :nombre_tarjeta, 'Nombre en la tarjeta' %>
      <%= form.text_field :nombre_tarjeta %>
    </div>

    <div class="field">
      <%= form.label :numero_tarjeta, 'Número de tarjeta' %>
      <%= form.text_field :numero_tarjeta %>
    </div>

    <!-- Agregar más campos según sea necesario (por ejemplo, fecha de vencimiento, código de seguridad, etc.) -->

    <div class="actions">
      <%# <%= form.submit 'Pagar'  %>
      <%= link_to "Paga", bookings_path, class: "btn btn-primary" %>
    </div>
  <% end %>
<% else %>
  <!-- Manejar el caso en el que @booking es nil, por ejemplo, mostrar un mensaje de error -->
  <p>Error: No se pudo obtener la información de la reserva.</p>
<% end %>

app/views/bookings/new.html.erb
<!-- app/views/bookings/new.html.erb -->
<h1>Nueva Reserva</h1>

<%= render 'form', booking: @booking, subjects: @subjects%>


  </div>

app/views/bookings/show.html.erb
<div class="container mt-4">
  <h1>Detalles de la Reserva</h1>

  <div class="card">
    <div class="card-body">
      <p class="card-text">Fecha: <%= @booking.date %></p>
      <p class="card-text">Hora de inicio: <%= @booking.time_in %></p>
      <p class="card-text">Hora de finalización: <%= @booking.time_out %></p>
      <p class="card-text">Materia: <%= @booking.subject.name %></p>

      <% if @booking.professor.present? %>
        <p class="card-text">Profesor: <%= @booking.professor.name %></p>
        <img src="<%= @booking.professor.photo_url %>" alt="Foto del Profesor" class="img-fluid" style="max-width: 100px; max-height: 100px;">
        <p class="card-text">Descripción del Profesor: <%= @booking.professor.description %></p>
      <% else %>
        <p class="card-text">Profesor no disponible</p>
      <% end %>

      <!-- Edit, Delete, and Back buttons -->
      <div class="btn-group" role="group">
        <%= link_to 'Editar', edit_booking_path(@booking), class: 'btn btn-warning' %>
        <%= link_to 'Eliminar', booking_path(@booking), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger', remote: true %>
        <%= link_to 'Volver a la lista de reservas', bookings_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutoriarte</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>

    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<%= render "shared/banner" %>

app/views/reviews/index.html.erb
<div class="container mt-5">
  <h2>Comentarios Creados </h2>
  <% @reviews.each do |review| %>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-text">Profesor: <%="#{review.user.first_name}#{review.user.last_name}" %></h5>
        <p class="card-title">Valoración: <%= review.rating %></p>
        <p class="card-text">Comentario: <%= review.comments %></p>
        <%= form_tag review_path(review), method: :delete, data: { confirm: '¿Estás seguro?' } do %>

        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'Genera un nuevo comentario', new_review_path, class: 'btn btn-primary btn-lg mx-auto' %>
<%= submit_tag 'Eliminar', class: 'btn btn-danger' %>

app/views/reviews/new.html.erb
  <div class="container mt-5">
  <h2 class="mb-4">Agrege su Comentario</h2>
<br>
  <%= simple_form_for [@user, @review] do |f| %>
  <%= hidden_field_tag :calificated_user, params[:teacher_id] %>
    <div class="mb-3">
    <%#= f.input :user, label:"Profesor:", prompt: "Seleccione un profesor", class: "form-select form-control-lg"%>
    <%#= raise %>
    </div>
    <%# aca se tiene q escribir  collection y el id que se determino a teacher, ya que si lo escribo ahora me arroja error %>
    <div class="mb-3">
      <label for="rating" class="form-label">Valoración:</label>
       <%= f.range_field :rating, in: 1..10, class: "form-range" %>
      <%# <input type="range" class="form-range" id="rating" name="rating" min="1" max="10"> %>
      <div class="d-flex justify-content-between">
        <span class="fw-bold">1</span>
        <span class="fw-bold">2</span>
        <span class="fw-bold">3</span>
        <span class="fw-bold">4</span>
        <span class="fw-bold">5</span>
        <span class="fw-bold">6</span>
        <span class="fw-bold">7</span>
        <span class="fw-bold">8</span>
        <span class="fw-bold">9</span>
        <span class="fw-bold">10</span>
      </div>
    </div>
    <%# <%= f.input :rating, label: "Valoracion", as: :range, in: 1..10 %>
    <div class="mb-3">
      <%= f.input :comments, label: "Agrague su comentario", as: :text, input_html: { rows: 4, class: "form-control" } %>
    </div>
    <div class="mb-3">
      <%= f.submit "Enviar", class: "btn btn-primary btn-lg" %>
    <br>
      <%#= link_to "Ir a Booking", bookings_path, class: "btn btn-secondary btn-lg" %>
  <% end %>

</div>

app/views/shared/_banner.html.erb
<div class="banner gradient">
  <div class="container">
    <h1>¡Bienvenid@ a <strong>nuestra gran comunidad</strong>!</h1>
    <p>Dónde estudiantes y profesores conectan</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    © 2023 TutoriArte
  </div>
  <div class="footer-links">
    <%= link_to 'About', about_path %>
    <%= link_to 'Contact', contact_path %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dgwpse2wf/image/upload/v1701222145/logo_ywxodh.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Encuentra un profesor", teachers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mis clases", bookings_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item">
            <%= link_to "Dashboard", "#", class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item">
            <%= link_to "Mensajes", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar" %>
            <% else %>
              <%= image_tag "https://res.cloudinary.com/dgwpse2wf/image/upload/v1701733180/undefined_user_rcbpiz.jpg", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

app/views/subjects/_form.html.erb
<%= simple_form_for(subject) do |f| %>
  <%= f.input :name %>
  <%= f.input :grade %>
  <%= f.submit %>
<% end %>

app/views/subjects/edit.html.erb
<div class="container mt-5">
<h2 class="card-title">Editar materia</h2>
  <br>
  <%= simple_form_for(@subject) do |f| %>
    <%= f.input :name %>
    <%= f.input :grade_subject, collection: ['1º Secundaria', '2º Secundaria', '3º Secundaria', '1º Preparatoria', '2º Preparatoria', '3º Preparatoria' ], prompt: 'Selecciona una opción' %>
    <%= f.input :description %>
    <%= f.submit "Guardar", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/subjects/index.html.erb
<div class="container mt-5">
  <h1 class="mb-3">My subjects</h1>
  <ul class="list-group">
    <% @subjects.each do |subject| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= subject.name %>
        <%= link_to "Ver más", subject_path(subject), class: "btn btn-info btn-sm" %>
      </li>
    <% end %>
  </ul>

  <%= link_to "Crear materia", new_subject_path, class: "btn btn-primary mt-3" %>
</div>

app/views/subjects/new.html.erb
<div class="container mt-5">
  <h2 class="card-title">Nueva materia</h2>
  <br>
  <%= simple_form_for(@subject) do |f| %>
    <%= f.input :name %>
    <%= f.input :grade_subject, collection: ['1º Secundaria', '2º Secundaria', '3º Secundaria', '1º Preparatoria', '2º Preparatoria', '3º Preparatoria' ], prompt: 'Selecciona una opción' %>
    <%= f.input :description %>
    <%= f.submit "Crear materia", class: 'btn btn-primary'  %> <%= link_to "Regresar al inicio", subjects_path, class: %>
  <% end %>
</div>

app/views/subjects/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title"><%= @subject.name %></h2>

      <p class="card-text">
        <strong>Grado:</strong> <%= @subject.grade_subject %>
      </p>

      <p class="card-text">
        <strong>Descripción:</strong> <%= @subject.description %>
      </p>

      <div>
        <%= link_to "Edit", edit_subject_path(@subject), class: "btn btn-outline-success mr-2" %>
        <%= link_to "Delete", subject_path(@subject), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "¿Seguro que quieres borrar la materia?" } %>
      </div>
    </div>
  </div>
</div>

app/views/teachers/index.html.erb
<div class="container">
  <h1 class="text-center mt-5 mb-5">Conoce a Nuestros Profesores</h1>

  <div class="card-group">
    <div class="row">
      <% @users.all.each do |user| %>
        <% if user.role == "Profesor" %>
          <div class="col-3">
            <div class="card mb-3" style="width: 18rem;">
              <% if user.photo.attached? %>
                <%= image_tag user.photo, class: "card-img-top", alt: "foto de perfil del profesor" %>
              <% else %>
                <%= image_tag "https://res.cloudinary.com/dgwpse2wf/image/upload/v1701733180/undefined_user_rcbpiz.jpg", class: "card-img-top", alt: "falta foto de perfil del profesor" %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title text-center"><%= user.first_name %> <%= user.last_name %></h5>
                <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
                <div class="container row">
                  <%= link_to "Perfil del Profe", teacher_path(id: user.id), class: "btn btn-primary mx-2 mb-1" %>
                  <%= link_to t('.Reserva'), new_booking_path, class: "btn btn-primary mx-2" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>




<%#= link_to 'Reservar Clase', '#', class: 'btn btn-primary', data: { toggle: 'modal', target: '#myModal' } %>

  <%# <%= turbo_frame_tag "modal" %>


<!-- En tu vista index.html.erb o donde sea que quieras que aparezca el modal -->

<!-- app/views/articles/index.html.erb -->
<%#= cl_image_tag("https://res.cloudinary.com/dgwpse2wf/image/upload/v1701540886/naig8e2momn4pyxt8hnh.jpg",
      width: 400, height: 300, crop: :fill) %>

<!-- for face detection -->
<%# <%= cl_image_tag("IMAGE_WITH_FACE_ID",
      width: 150, height: 150, crop: :thumb, gravity: :face) %>

app/views/teachers/show.html.erb
<div class="container">
  <% if @user.photo.attached? %>
    <%= image_tag @user.photo, width: 150, height: 150, alt: "foto de perfil del profesor" %>
  <% else %>
    <%= image_tag "https://res.cloudinary.com/dgwpse2wf/image/upload/v1701733180/undefined_user_rcbpiz.jpg", width: 150, height: 150, alt: "falta foto de perfil del profesor" %>
  <% end %>
  <h3><%= @user.first_name %> <%= @user.last_name %></h3>
  <p> Ciudad: <%= @user.city %></p>

</div>

<div class="container">
  <%= link_to t('.Resevar'), new_booking_path, class: "btn btn-primary mx-2" %>
  <%= link_to "Calificar", new_teacher_review_path(@user), class: "btn btn-primary mx-2" %>
</div>

<%# Subjects %>
<div class="container">
  <div class="container mt-5">
    <h1 class="mb-3">Materias del Profesor</h1>
    <ul class="list-group">
      <% @subjects.each do |subject| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <%= subject.name %>
          <%= link_to "Ver más", subject_path(subject), class: "btn btn-info btn-sm" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%# Subjects %>
<div class="container">
  <div class="container mt-5">
    <h1 class="mb-3">Calificaciones de sus Estudiantes</h1>
    <ul class="list-group">
      <% @reviews.each do |review| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p class="card-text"><%= review.comments %></p>
          <p class="card-title">Rating: <%= review.rating %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>